# Spectral OpenAPI Linting Configuration
# https://meta.stoplight.io/docs/spectral/

extends:
  - spectral:oas

rules:
  # Require operation IDs for all operations
  operation-operationId: error

  # Require descriptions for all operations
  operation-description: warn

  # Require tags for all operations
  operation-tags: warn

  # Require examples in all responses
  oas3-valid-media-example: warn

  # Ensure all operations have success response
  operation-success-response: warn

  # Require contact information
  info-contact: warn

  # Require license information
  info-license: warn

  # Require API description
  info-description: warn

  # Prevent duplicate operation IDs
  operation-operationId-unique: error

  # OpenAPI 3.1 uses nullable differently - disable this check
  oas3-schema: off

  # Disable unused component checks for now
  oas3-unused-component: off

  # Tag names should be lowercase with hyphens
  tag-names-kebab-case:
    severity: warn
    given: $.tags[*].name
    then:
      function: pattern
      functionOptions:
        match: '^[a-z][a-z0-9-]*$'
