name: Feature Request
description: Suggest a new feature or enhancement
title: "[FEATURE] "
labels: ["enhancement", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible to help us understand your request.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm frustrated when...
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: A clear and concise description of what you want to happen
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe alternatives you've considered
      placeholder: A clear and concise description of any alternative solutions or features you've considered
    validations:
      required: false

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature is this?
      options:
        - New Functionality
        - Enhancement to Existing Feature
        - Performance Improvement
        - Developer Experience
        - Documentation
        - Testing
        - CI/CD
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical - Blocking current work
        - High - Would significantly improve workflow
        - Medium - Nice to have
        - Low - Minor improvement
    validations:
      required: true

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Describe the use cases for this feature
      placeholder: |
        1. As a [user type], I want to [action] so that [benefit]
        2. ...
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: What would make this feature complete?
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
        - [ ] Criterion 3
    validations:
      required: false

  - type: textarea
    id: technical-details
    attributes:
      label: Technical Details
      description: Any technical implementation details or suggestions
      placeholder: Implementation suggestions, API changes, database schema changes, etc.
    validations:
      required: false

  - type: dropdown
    id: breaking-change
    attributes:
      label: Breaking Change
      description: Would this feature introduce breaking changes?
      options:
        - "No"
        - "Yes"
        - "Possibly"
    validations:
      required: true

  - type: textarea
    id: breaking-details
    attributes:
      label: Breaking Change Details
      description: If yes or possibly, please describe the breaking changes
      placeholder: Describe what would break and how to migrate...
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request
      placeholder: Any additional information...
    validations:
      required: false

  - type: textarea
    id: resources
    attributes:
      label: Resources
      description: Links to relevant documentation, similar implementations, or research
      placeholder: |
        - Link 1
        - Link 2
    validations:
      required: false

  - type: checkboxes
    id: implementation
    attributes:
      label: Implementation Willingness
      description: Are you willing to help implement this feature?
      options:
        - label: I am willing to submit a pull request for this feature
          required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please verify the following before submitting
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have included all relevant information above
          required: true
